- name: Install and configure Jenkins and Nexus
  hosts: all
  tasks:
    - name: Ensure Python is installed
      raw: sudo apt update && sudo apt install -y python3

- name: Setup Jenkins on master
  hosts: jenkins
  become: yes
  tasks:
    - name: Install Java 17 on Jenkins server
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Add Jenkins repository key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      become: yes

    - name: Add Jenkins repository to sources list
      shell: |
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      become: yes

    - name: Update apt repository cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Jenkins on Jenkins server
      apt:
        name: jenkins
        state: present
        update_cache: yes
      become: yes

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
      become: yes

- name: Setup Nexus on nexus
  hosts: nexus
  become: yes
  tasks:
    - name: Ensure nexus user exists
      user: 
        name: nexus
        state: present
        shell: /bin/bash
      become: yes  

    - name: Install Java 11 on Nexus server
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    # - name: Create Nexus user and set up permissions
    #   user:
    #     name: nexus
    #     state: present
    #     shell: /bin/bash
    #     create_home: yes
    #     home: /opt/nexus
    #     system: yes
    #   become: yes

    - name: Ensure proper permissions on Nexus directory
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        mode: '0755'
      become: yes

    - name: Create Nexus service file
      copy:
        dest: /etc/systemd/system/nexus.service
        content: |
          [Unit]
          Description=Nexus Repository Manager
          After=network.target
          
          [Service]
          Type=simple
          User=nexus
          Group=nexus
          ExecStart=/opt/nexus/bin/nexus start
          ExecStop=/opt/nexus/bin/nexus stop
          Restart=on-failure
          Environment=JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          Environment=PATH=$JAVA_HOME/bin:$PATH

          [Install]
          WantedBy=multi-user.target
      become: yes

    - name: Reload systemd and start Nexus service
      systemd:
        name: nexus
        state: started
        enabled: yes
      become: yes
      notify:
        - Reload systemd

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
      become: yes



