- name: Install and configure Jenkins and Nexus
  hosts: all
  tasks:
    - name: Ensure Python is installed
      raw: sudo apt update && sudo apt install -y python3

- name: Setup Jenkins on master
  hosts: jenkins
  become: yes
  tasks:
    - name: Install Java and required packages on Jenkins server
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - openjdk-11-jdk
        - maven
        - docker.io
        - jenkins
        - git

    - name: Enable and start Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

- name: Setup Nexus on nexus
  hosts: nexus
  become: yes
  tasks:
    - name: Install Docker on Nexus server
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Run Nexus container
      docker_container:
        name: nexus
        image: sonatype/nexus3
        state: started
        ports:
          - "8081:8081"
        restart_policy: always


